service: alki-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    FRONTEND_URL: ${env:FRONTEND_URL} 
    AUTH0_DOMAIN: ${env:AUTH0_DOMAIN} 
    AUTH0_AUDIENCE: ${env:AUTH0_AUDIENCE}
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}



package:
  patterns:
    - '!node_modules/**' # Let serverless-esbuild handle dependencies
    - '!src/**' # Exclude source files (only include /dist)

functions:
  api:
    handler: dist/lambda.handler # Path to compiled handler
    events:
      - httpApi: '*'