export {default as NotFound} from "./NotFound/NotFound"
export {default as LoginPage} from "./Login/Login"
export {default as SignUpPage} from "./SignUp/SignUp"
export {default as AddProperty} from "./Properties/AddProperty"
export {default as AddTenant} from "./Tenants/AddTenant"
export {default as AddInventory} from "./Inventories/AddInventory"
export {default as Settings} from "./Settings/Settings"
export {default as Organizations} from './Organizations/Organizations'
export {default as PostLogin} from './Login/PostLogin'
export {default as Onboarding} from './Onboarding/Onboarding'
export {default as Properties} from './Properties/Properties'
export {default as TenantPayments} from './Payments/TenantPayments'
export {default as Services} from './Services/Services'